### ISSUE TITLE
Error, can't do anything...

### ISSUE THREAD

**Issue by alienbogart** [isamert/orgmdb.el#7]
Contacting host: www.omdbapi.com:80
Decrypting /home/dave/.emacs.d/.local/etc/authinfo.gpg...done
error in process filter: epa-file-insert-file-contents: Opening input file: Decryption failed, 
error in process filter: Opening input file: Decryption failed,

**Comment by isamert** [comment]
Which function did you run? Can you do `M-x toggle-debug-on-error` and send me the error output?

**Comment by alienbogart** [comment]
> Which function did you run? Can you do `M-x toggle-debug-on-error` and send me the error output?

I'm at a loss, to be honest. The error is gone, but I created the API key, and now when I try using it it asks for my username and password. I did not create a username/password on this package. What's it asking for? Thanks.

**Comment by isamert** [comment]
orgmdb uses `url-retrieve-synchronously` to retrieve omdb api response. I believe due to your current setup, it tries to open some files and for some reason it fails. Can you try to run the following elisp:

```
(switch-to-buffer (url-retrieve-synchronously "https://gnu.org"))
``` 

It should display the html contents for gnu.org in a buffer. Can you confirm if it works or not?

Sorry for the late response, this one got lost on the notifications I guess.

**Comment by isamert** [comment]
Closing this, if you still have the issue please re-open or create a new issue.
